language: cpp
compiler:
  - clang


# whitelist
branches:
  only:
    - travis 

# Install pre-reqs
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get clean -qq
  - sudo apt-get update -qq
  - sudo apt-get install -y -f build-essential python-psutil libfuse-dev libicu-dev
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
  - tar xf cmake-2.8.12.2.tar.gz
  - cd cmake-2.8.12.2
  - ./bootstrap
  - make
  - sudo make install
  - cd ../..

# Run the Build script
before_script:
  - cmake -HMaidSafe -Bbuild_maidsafe -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang
  - cd build_maidsafe

script: 
  - make
